### ISSUE TITLE
`--overrides` are not applied when using `oc expose service` to create a route

### ISSUE THREAD

**Issue by JustinKuli** [openshift/oc#1219]
In previous versions of `oc` (tested with 4.9.x and 4.10.x), it was possible to create a route by exposing a service, and specify the TLS termination by providing it in an `--overrides` argument. For example:
```
oc expose service nginx --overrides='{"spec":{"tls":{"termination":"reencrypt"}}}'
```

But in a recent 4.11.x version of `oc`, this does not work as intended - the route is created, but does not have the `reencrypt` setting.

Other things that could be specified in the overrides (ie annotations) are also being ignored in the latest version. I think the issue is caused by no longer using a generator for the route, and instead creating it directly, here: https://github.com/openshift/oc/blob/master/pkg/cli/expose/expose.go#L187

## Steps to recreate the problem

1. Create an nginx deployment: `oc apply -f https://k8s.io/examples/application/deployment.yaml`
2. Expose the deployment as a service: `oc expose deployment nginx-deployment`
3. Expose the service as a route with an override: `oc expose service nginx-deployment --overrides='{"spec":{"tls":{"termination":"reencrypt"}}}'`
4. Check the created route:

```
# With oc 4.9.x : 
❯ oc get route nginx-deployment -o yaml | grep -A 10 spec:
spec:
  host: [elided]
  port:
    targetPort: 80
  tls:
    termination: reencrypt
  to:
    kind: Service
    name: nginx-deployment
    weight: 100
  wildcardPolicy: None

# With oc 4.11.x : 
❯ oc get route nginx-deployment -o yaml | grep -A 10 spec:
spec:
  host: [elided]
  port:
    targetPort: 80
  to:
    kind: Service
    name: nginx-deployment
    weight: 100
  wildcardPolicy: None
status:
  ingress:
```
