### ISSUE TITLE
namespace variable in bc metadata conflicts with --namespace flag

### ISSUE THREAD

**Issue by micheal-w-wells** [openshift/oc#1223]
OC CLI Version: Client Version: 4.11.0 Kustomize Version: v4.5.4 (currently in GH action runner Ubuntu 20.04 images starting today).

Requires templates to have 'namespace' set in metadata, however unable to use parameter in metadata of template, and otherwise hard coding it results in error saying there is no namespace flag being passed in.

Example bc:

This does not work: ```oc --namespace=namespaceName process -f app.bc.yaml```

```
apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  labels:
    build: app_name
  name: app_name
  namespace: namespaceName
  ```
  
  Neither does defining a param and passing it in via --param=ParamName=namespaceName.  
  
  
  All result in error complaining that the template value does not match "" and indicates that the namespace flag is not passed in:
  
  ```
  error: failed to read input object (not a Template?): the namespace from the provided object "nameSpaceName" does not match the namespace "". You must pass '--namespace=nameSpaceName' to perform this operation.
  ```
