### ISSUE TITLE
oc new-app with s2i repository doesn't add sourcecode annotation ref

### ISSUE THREAD

**Issue by jerolimov** [openshift/oc#1373]
When importing an application with the OKD or OpenShift Developer console, the topology shows a link ("Source code decorator") that opens GitHub or my source code directly.

But when importing the same application via `oc new-app` this link/decorator isn't shown because the oc command doesn't apply the necessary annotation `app.openshift.io/vcs-uri`  for it. It might be creat if the new-app command set this as well if a git repository is used.

The left side is created via the console, right side with the `oc new-app` command below. Top-right decorator is missing:

![image](https://user-images.githubusercontent.com/139310/225672902-25f92924-1968-4a89-a70c-a29f00d1a764.png)

Used command:

```sh
oc new-app nodejs:latest~https://github.com/sclorg/nodejs-ex.git
```

Here is a snippet with the annotations that the web console creates:

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    app.openshift.io/vcs-uri: 'https://github.com/sclorg/nodejs-ex'
    app.openshift.io/vcs-ref: '' # not empty when defining a branch, tag, or commit
    ...
```
