### ISSUE TITLE
oc expose generates invalid hostname if namespace or service name is too long

### ISSUE THREAD

**Issue by pmacik** [openshift/oc#486]
I have:
* service: `nodejs-rest-http-crud`
* namespace: `test-namespace-2a55e626-8028-45e7-a353-25c8317d1b16` which is valid

```
$ oc version

Client Version: 4.5.0-rc.6
Server Version: 4.5.0-rc.6
Kubernetes Version: v1.18.3+6025c28
```

When i try to expose the service to a route, I get:
```
$ oc expose service nodejs-rest-http-crud -n test-namespace-2a55e626-8028-45e7-a353-25c8317d1b16 

route.route.openshift.io/nodejs-rest-http-crud exposed
```

```
$ oc get routes

NAME                    HOST/PORT     PATH   SERVICES                PORT       TERMINATION   WILDCARD
nodejs-rest-http-crud   InvalidHost          nodejs-rest-http-crud   8080-tcp                 None
```

```
$ oc get route nodejs-rest-http-crud -o yaml 
```
```yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
...
  name: nodejs-rest-http-crud
  namespace: test-namespace-2a55e626-8028-45e7-a353-25c8317d1b16
...
status:
  ingress:
  - conditions:
    - lastTransitionTime: "2020-07-07T14:29:55Z"
      message: 'host name validation errors: spec.host: Invalid value: "nodejs-rest-http-crud-test-namespace-2a55e626-8028-45e7-a353-25c8317d1b16.apps.helm-acc-tests-pm-1.devcluster.openshift.com":
        must be no more than 63 characters'
      reason: InvalidHost
      status: "False"
      type: Admitted
    host: nodejs-rest-http-crud-test-namespace-2a55e626-8028-45e7-a353-25c8317d1b16.apps.helm-acc-tests-pm-1.devcluster.openshift.com
    routerCanonicalHostname: apps.helm-acc-tests-pm-1.devcluster.openshift.com
    routerName: default
    wildcardPolicy: None
```
