### ISSUE TITLE
oc project not works with cluster proxy.

### ISSUE THREAD

**Issue by wanghaoran1988** [openshift/oc#647]
We are using a proxy as the apiserver that can reverse proxy to multiple clusters, so we has config like:
```
apiVersion: v1
clusters:
- cluster:
    server: http://localhost:8001/backplane/cluster/1h2cu64jqeufe3dnk7gvpl7j3ui3msut/
  name: 1h2cu64jqeufe3dnk7gvpl7j3ui3msut
contexts:
- context:
    cluster: 1h2cu64jqeufe3dnk7gvpl7j3ui3msut
    namespace: openshift-logging
    user: haoran.openshift
  name: default/1h2cu64jqeufe3dnk7gvpl7j3ui3msut/haoran.openshift
current-context: default/1h2cu64jqeufe3dnk7gvpl7j3ui3msut/haoran.openshift
kind: Config
preferences: {}
users:
- name: haoran.openshift
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - /Users/haowang/.kube/ocm-token
      command: bash
      env: null
```
When we perform oc project <project>
It will create a new context&server&user as follows:
```
apiVersion: v1
clusters:
- cluster:
    server: http://localhost:8001/backplane/cluster/1h2cu64jqeufe3dnk7gvpl7j3ui3msut/
  name: 1h2cu64jqeufe3dnk7gvpl7j3ui3msut
- cluster:
    server: http://localhost:8001/backplane/cluster/1h2cu64jqeufe3dnk7gvpl7j3ui3msut/
  name: localhost:8001
contexts:
- context:
    cluster: 1h2cu64jqeufe3dnk7gvpl7j3ui3msut
    namespace: openshift-monitoring
    user: haoran.openshift
  name: default/1h2cu64jqeufe3dnk7gvpl7j3ui3msut/haoran.openshift
- context:
    cluster: localhost:8001
    namespace: default
    user: system:serviceaccount:openshift-backplane-srep:89bb76f8aa82917707763cfb8c4a01a5/localhost:8001
  name: default/localhost:8001/system:serviceaccount:openshift-backplane-srep:89bb76f8aa82917707763cfb8c4a01a5
current-context: default/localhost:8001/system:serviceaccount:openshift-backplane-srep:89bb76f8aa82917707763cfb8c4a01a5
kind: Config
preferences: {}
users:
- name: haoran.openshift
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - /Users/haowang/.kube/ocm-token
      command: bash
      env: null
- name: system:serviceaccount:openshift-backplane-srep:89bb76f8aa82917707763cfb8c4a01a5/localhost:8001
  user: {}
```

oc project should respect the current context, and only change the namespace in the current-context
